name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install required Android SDK components
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Verify project layout
        run: |
          echo "== Top-level files =="
          ls -la
          echo "== app/src/main listing =="
          ls -la app/src/main || true
          echo "== Checking required files =="
          for f in \
            app/src/main/AndroidManifest.xml \
            app/src/main/java/com/mudrahub/MainActivity.kt \
            app/build.gradle.kts \
            settings.gradle.kts \
            gradle.properties
          do
            if [ -f "$f" ]; then 
              echo "Found: $f"
            else 
              echo "Missing: $f" && missing=1
            fi
          done
          test -z "${missing:-}" || (echo "Missing required files. See above." && exit 1)

      - name: Regenerate Gradle wrapper
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          rm -f gradlew gradlew.bat
          rm -rf gradle/wrapper
          gradle wrapper --gradle-version 8.7
          chmod +x ./gradlew
          ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MudraHub-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
