name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # Install cmdline tools + required SDK packages
      - name: Install Android Command-Line Tools + SDK
        run: |
          set -e
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          curl -L -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q sdk-tools.zip -d latest
          rm sdk-tools.zip
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # If wrapper files aren’t in the repo, create them
      - name: Ensure Gradle wrapper
        run: |
          set -e
          if [ ! -f ./gradlew ] || [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Gradle wrapper missing — generating…"
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MudraHub-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
