name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      # Ensure the platform/build-tools you compile against are present
      - name: Install required Android SDK components
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      # Generate a fresh wrapper if the repo doesn't have one; make it executable
      - name: Ensure Gradle wrapper
        run: |
          if [ ! -f ./gradlew ]; then
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew
          ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MudraHub-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
