name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Install cmdline tools + the *exact* packages we need
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      # Force non-interactive license acceptance (even if the previous step tries to prompt)
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses >/dev/null

      - name: Ensure Gradle wrapper
        run: |
          if [ ! -f ./gradlew ]; then
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew

      - name: Build Debug APK (show Kotlin errors clearly if any)
        run: |
          ./gradlew :app:compileDebugKotlin --stacktrace --info --no-daemon
          ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MudraHub-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
